path: D:\Github\web-court\tf\yolo\data
train: images\train3
val: images\val

#classes
nc: 11
names:
  0: scheda-punti-numero-1
  1: scheda-testo-1
  2: scheda-testo-0
  3: scheda-numerone-1
  4: scheda-puntata-numero-2
  5: scheda-testo-2
  6: scheda-testo-3
  7: scheda-testo-2.1
  8: scheda-1
  9: scheda-2
  10: scheda-punti-numero-0